### ISSUE TITLE
HONConduct287962 - Unknown country code

### ISSUE THREAD

**Issue by williambelle** [healthonnet/hon-honcode-extension#107]
**Summary**

On the site http://vakulenko.dn.ua/, the country flag is not displayed.

**Steps to reproduce**

1. Go to http://vakulenko.dn.ua/

**Environment**

* Chrome 63.0.3239.108
* HONcode Toolbar 3.1.1

**Screenshot**

![honconduct287962](https://user-images.githubusercontent.com/2843501/34257848-dee41d26-e65b-11e7-9f51-176aab488ef7.png)

**Comment by williambelle** [comment]
See https://www.myhealthonnet.org/index.php/en/?option=com_honcodemembership&controller=honcodeseniority&task=getSeniority&honconduct=HONConduct287962

```json
{
  "first_certification": 1494993600,
  "years": 0,
  "last_certification": 1494993600,
  "validity": 1526529600,
  "country": "SU",
  "type": "Individual",
  "popularity": 1,
  "alexa_rank": 13955452
}
```

`SU` is not a correct code.

@Pepper-and-mint Can you find the correct country ?

**Comment by Pepper-and-mint** [comment]
Seems fixed.
