### ISSUE TITLE
HONConduct657216 - Missing country code

### ISSUE THREAD

**Issue by williambelle** [healthonnet/hon-honcode-extension#108]
**Summary**

On the site https://www.infosagehealth.org/, the country flag is not displayed.

**Steps to reproduce**

1. Go to https://www.infosagehealth.org/

**Environment**

* Chrome 63.0.3239.108
* HONcode Toolbar 3.1.1

**Screenshot**

![honconduct657216](https://user-images.githubusercontent.com/2843501/34258619-fbfecc3c-e65e-11e7-99ff-7dee3c44b5a4.png)

**Comment by williambelle** [comment]
See https://www.myhealthonnet.org/index.php/en/?option=com_honcodemembership&controller=honcodeseniority&task=getSeniority&honconduct=HONConduct657216

```json
{
  "first_certification": 1450674000,
  "years": 1,
  "last_certification": 1484542800,
  "validity": 1516078800,
  "country": null,
  "type": "Organization",
  "popularity": 1,
  "alexa_rank": 10000000
}
```

@Pepper-and-mint Can you find the country ?

**Comment by Pepper-and-mint** [comment]
USA added to the file

**Comment by Pepper-and-mint** [comment]
Ok now
