### ISSUE TITLE
HONConduct479480 - Missing country code

### ISSUE THREAD

**Issue by williambelle** [healthonnet/hon-honcode-extension#109]
**Summary**

On the site http://consumers.cochrane.org/, the country flag is not displayed.

**Steps to reproduce**

1. Go to http://consumers.cochrane.org/

**Environment**

* Chrome 63.0.3239.108
* HONcode Toolbar 3.1.1

**Screenshot**

![honconduct479480](https://user-images.githubusercontent.com/2843501/34258740-a0ee39f8-e65f-11e7-973a-f53569cf3566.png)

**Comment by williambelle** [comment]
See https://www.myhealthonnet.org/index.php/en/?option=com_honcodemembership&controller=honcodeseniority&task=getSeniority&honconduct=HONConduct479480

```json
{
  "first_certification": 1284091200,
  "years": 1,
  "last_certification": 1322629200,
  "validity": 1385787600,
  "country": null,
  "type": "Non-profit",
  "popularity": 3,
  "alexa_rank": 35957
}
```

@Pepper-and-mint Can you find the country ?

**Comment by Pepper-and-mint** [comment]
I added UK to the HONuser file
