### ISSUE TITLE
Missing spanish translation (app description)

### ISSUE THREAD

**Issue by williambelle** [healthonnet/hon-honcode-extension#48]
See

<img width="350" alt="chrome-store-es" src="https://cloud.githubusercontent.com/assets/2843501/23037483/d36bac7e-f486-11e6-9450-184a5809adf3.png">

**Comment by williambelle** [comment]
@Pepper-and-mint can you take a look when you have time.

Thanks

**Comment by Pepper-and-mint** [comment]
@williambelle Ok vu, mais je ne sais pas comment on fait le changement, il faut "Importer le package mis à jour" en zip pour changer cette partie de la description, c'est indépendant du texte que je peux modifier.

**Comment by williambelle** [comment]
@Pepper-and-mint il faut traduire le texte dans Loco (appDescription). Après, c'est mis à jour automatiquement quand vous ferez la release 2.2.0

**Comment by Pepper-and-mint** [comment]
Ok done
