### ISSUE TITLE
Dates of first certification not correct

### ISSUE THREAD

**Issue by williambelle** [healthonnet/hon-honcode-extension#65]
**Summary**

The dates of first certification are not always correct.

**Steps to reproduce**

1. Go to http://www.nvog.nl/
2. Go to https://www.hon.ch/HONcode/Conduct.html?HONConduct042239
3. Compare the dates (10 May 2011, 14 Jan 1997)

**Environment**

* Chrome 61.0.3163.100
* HONcode Toolbar 3.0.0

**Screenshot**

<img width="250" alt="honconduct042239" src="https://user-images.githubusercontent.com/2843501/31133020-98d8329e-a85e-11e7-8d13-cfb7bf6b37b5.png">

**Comment by Adrion** [comment]
@Pepper-and-mint can you please check the history of HONConduct042239 and confirm the initial review date ? Thank you
https://www.hon.ch/HONcode/Conduct.html?HONConduct042239

**Comment by Pepper-and-mint** [comment]
First DeliverSeal 10 May 2011

**Comment by Adrion** [comment]
@baujardv it seems that we have some issues with initial reviews dates

**Comment by williambelle** [comment]
So the dates of first certifications are correct but the calculation of the loyalty is incomprehensible for me.

as a user, I make the following calculation: 
```
First DeliverSeal 10 May |    2011
loyalty                  | +    14
----------------------------------
                              2025
```
and I'm totally wrong...

If I do:
```
Initial Review 14 Jan |   1997
loyalty               | +   14
------------------------------
                          2011
```
I miss 2 years (valid until 2013).

I imagine that in the controller (`honcodeseniority`), we just do:

```php
diff($dateValid, $dateInitReview)
```

and that it is too simplistic?

I don't remember  😞

**Comment by Adrion** [comment]
```
/**
	 * get years of certification from honConduct certificate
	 *
	 * @param   int  $dateValidity       honConduct date validity
	 * @param   int  $dateInitialReview  honConduct date initial review
	 *
	 * @access  public
	 * @return  int
	 *
	 * @since  available since version 0.0.29
	 */
	public function getYears($dateValidity, $dateInitialReview)
	{
		$interval = 0;
		$validity = new DateTime;
		$validity->setTimestamp((int) $dateValidity);
		$initial = new DateTime;
		$initial->setTimestamp((int) $dateInitialReview);

		if ($validity->getTimestamp() == 0 || $initial->getTimestamp() == 0)
		{
			return 0;
		}

		$interval = $validity->diff($initial);

		$interval = (int) $interval->format('%y');

		return $interval;
	}
```

**Comment by Adrion** [comment]
yes it seems that's a simple diff between initial and valid. 
We already speak about this limitation. If someone stop to certify his website for years and then do it again he'll have the all loyalty period

**Comment by Adrion** [comment]
the problem is the initial review date that should be : 10 May 2011 and set loyalty to only 2 years 
so : 
```
Valid until              |   2013
First DeliverSeal 10 May | - 2011
----------------------------------
Loyalty                         2
```
like a user would think.

The problem is honuser-side.

**Comment by Adrion** [comment]
We want to use the first review date
