### ISSUE TITLE
Wrong popularity for HONConduct513574

### ISSUE THREAD

**Issue by williambelle** [healthonnet/hon-honcode-extension#70]
**Summary**

The popularity is 5 whereas the alexa rank is 10 000 000.

**Steps to reproduce**

1. Go to http://oncorun.net/

**Environment**

* Chrome 61.0.3163.100
* HONcode Toolbar 3.1.0

**Screenshot**

![honconduct513574](https://user-images.githubusercontent.com/2843501/31435906-6f6eb634-ae81-11e7-9a1f-fdae47da8cc0.png)

**Comment by williambelle** [comment]
I'm not sure it's related but

![oncorun](https://user-images.githubusercontent.com/2843501/31454125-aee71ec2-aeb4-11e7-9019-19f11a996b8a.png)

**Comment by Adrion** [comment]
I checked and popularity is based on alexa_global_rank 
but alexaRank return in the service is actually the alexa_daily_rank.

But the question is why daily is empty (set to 10000000)  and global rank is `2391` ?
<img width="707" alt="capture d ecran 2017-10-12 a 11 37 03" src="https://user-images.githubusercontent.com/5418815/31489675-b9d292a2-af41-11e7-9418-f294664a8504.png">

@baujardv  any idea ?
