### ISSUE TITLE
HONConduct missing in MD5 list

### ISSUE THREAD

**Issue by williambelle** [healthonnet/hon-honcode-extension#74]
**Summary**

Some HONConduct are missing in the MD5 list.

**Steps to reproduce**

1. Go to https://www.honcode.ch/HONcode/Plugin/listeMD5.txt
2. Search 7509941a1950910483a8180de09706da

**Screenshot**

<img width="500" alt="missing" src="https://user-images.githubusercontent.com/2843501/32036459-3f8a9762-ba20-11e7-93a2-3b6a5bfcd1d1.png">

**Comment by Adrion** [comment]
@baujardv une idée ?

**Comment by williambelle** [comment]
@baujardv It's now partially corrected.

See:
  * fbba243f1f111029faf1dc1ceb95b2b5
  * c250605ec2bbe709883cfe30d77b3091
