### ISSUE TITLE
All dates of first certification set to 0

### ISSUE THREAD

**Issue by williambelle** [healthonnet/hon-honcode-extension#80]
**Summary**

It looks like all dates of first certification are set to 0.

**Steps to reproduce**

1. https://www.myhealthonnet.org/index.php/en/?option=com_honcodemembership&controller=honcodeseniority&task=getSeniority&honconduct=HONConduct298987
2. https://www.myhealthonnet.org/index.php/en/?option=com_honcodemembership&controller=honcodeseniority&task=getSeniority&honconduct=HONConduct736779

**Comment by Adrion** [comment]
Checked with @baujardv . A problem with bTree generation. Service is fixed
